<?php

namespace AppBundle\Repository;

/**
 * DisponibilidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
